# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /

# 日志配置
logging:
  level:
    cn.van.mall: debug
    org.springframework: warn

# Spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: mall
    password: mall
    driverClassName: com.mysql.cj.jdbc.Driver
# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: cn.van.mall.database.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml